### PR TITLE
Update setup guide in README, fix first run spam

### LINKED ISSUE #3: Tutorial for setup
The README should include a proper tutorial for setting up. Right now it isn't super clear and if the deploy with workers button breaks, there is no easy explanation for those not familiar with Workers.

### PR DESCRIPTION
**Pull request by MattIPv4**
:wave: This PR does a few small updates as I went about getting this running myself:

- Updates the instructions in the README to cover all the steps needed to run this (closes #3)
- Modifies the logic for posting new incidents slightly, skipping resolved incidents that were never posted, as to avoid spamming old incidents on the first run
- Updates the types dependency (as things like `Request` were undefined types), and adds wrangler as a dev dependency so it isn't reliant on a system-wide wrangler installation

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -44,11 +44,12 @@ export default {
...
       }
 
-      if (kv === null) {
-        await this.postNew(incident, env);
-      } else {
-        await this.postUpdate(incident, kv, env);
-      }
+      // If we've not seen this before, and it's already resolved, ignore it
+      // This stops us spamming old incidents on first run
+      if (kv === null && incident.status === 'resolved') return;
```
Comment (MattIPv4) [inline src/index.ts:49]: My only hesitation here is that this would break the detection of "retro" incidents that're posted in a resolved status from the start.

I could get around this by storing a new KV value that tracks if this is the first run, and writing these "skipped" incidents to KV with a different data format that indicates they were skipped.

Comment (WalshyDev) [reply src/index.ts:49]: Maybe we should [`KV.list`](https://developers.cloudflare.com/workers/runtime-apis/kv/#listing-keys) and if size is 0 then put all incidents into KV but don't post.

**Review by WalshyDev — COMMENTED** [review]
(Sorry for the delay)

This looks good, left a suggestion for how to handle the first run better

File: src/index.ts (hunk 1 above)
Comment (MattIPv4) [reply src/index.ts:49]: `KV.list` has a limit of 1,000 a day before being billed, and with this running every minute via cron, that'd mean 440 billed list calls each day. I'll go down the route of just storing a `firstRun` key in KV and check if that exists.

File: README.md [hunk 2]
```diff
@@ -7,23 +7,30 @@ We use this in the [Cloudflare Discord](https://discord.gg/cloudflaredev), come
...
+There are a few steps to the setup, but it should hopefully be pretty straightforward:
 
 1. Clone the repo
-2. Edit `src/config.ts` - here you can set the status URL, name of the webhook, avatar and publish channel
-3. Put your IDs in `wrangler.toml`
-4. Add Discord webhook with `wrangler secret put DISCORD_WEBHOOK` \
-  4b. (optional) If you want publishing, you'll also need to add a Discord bot token with `wrangler secret put DISCORD_TOKEN`
-5. Run `npm run publish` :)
+2. Edit `src/config.ts` to set the status URL, name of the webhook, avatar and publish channel
+3. Authenticate Wrangler with `npx wrangler login`, or set the `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` environment variables (or put them in `.env`)
```
Comment (WalshyDev) [inline README.md:14]: .env _works_ but i don't think we even document it. `.dev.vars` is the recommended way
```suggestion
3. Authenticate Wrangler with `npx wrangler login`, or set the `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN` environment variables (or put them in `.dev.vars`)
```

File: src/index.ts [hunk 3]
```diff
@@ -34,21 +34,28 @@ export default {
     const res = await fetch(`${Config.STATUS_URL}/api/v2/incidents.json`)
     const json = await res.json<IncidentResponse>();
 
-    await Promise.all(json.incidents.map(async incident => {
-      const kv = await env.KV.get<Incident>(incident.id, 'json');
+    // Track if this is the first run, so we can ignore resolved incidents
+    const firstRun = await env.KV.get('firstRun', 'text') === null;
```
Comment (WalshyDev) [inline src/index.ts:38]: no need to specify text, that's default and either way we don't mind how the content is delivered
```suggestion
    const firstRun = await env.KV.get('firstRun') === null;
```

File: src/index.ts [hunk 4]
```diff
@@ -34,21 +34,28 @@ export default {
...
+    if (firstRun) await env.KV.put('firstRun', new Date().toISOString());
```
Comment (WalshyDev) [inline src/index.ts:39]:
```suggestion
    if (firstRun) {
      await env.KV.put('firstRun', new Date().toISOString());
    }
```

File: src/index.ts [hunk 5]
```diff
@@ -34,21 +34,28 @@ export default {
...
 
+    await Promise.all(json.incidents.map(async incident => {
+      const kv = await env.KV.get<StoredIncident>(incident.id, 'json');
       console.log('-----\nIncident ' + incident.id + ' in KV: ' + (kv !== null) + '\n-----');
 
+      // On the first run, ignore any incidents that are already resolved
+      // We'll store them as skipped so we don't keep checking them
+      if (firstRun && incident.status === 'resolved') {
+        await env.KV.put(incident.id, JSON.stringify({ skipped: true }));
```
Comment (WalshyDev) [inline src/index.ts:48]: Wonder if we should just set a null value and use metadata instead. Not super opinionated on this though

File: src/index.ts [hunk 6]
```diff
@@ -34,21 +34,28 @@ export default {
...
         incident.updated_at = new Date().toISOString();
       }
-
-      if (kv === null) {
-        await this.postNew(incident, env);
-      } else {
-        await this.postUpdate(incident, kv, env);
-      }
+      if (kv === null) await this.postNew(incident, env);
+      else await this.postUpdate(incident, kv, env);
```
Comment (WalshyDev) [inline src/index.ts:58]: I hate inline if statements for anything other than return/continue 😅 
```suggestion
      if (kv === null) {
        await this.postNew(incident, env);
      } else {
        await this.postUpdate(incident, kv, env);
      }
```

File: README.md (hunk 2 above)
Comment (MattIPv4) [reply README.md:14]: 🤔 Are those env values read from `.dev.vars`? I thought `.dev.vars` was used for runtime secrets?

File: src/index.ts (hunk 5 above)
Comment (MattIPv4) [reply src/index.ts:48]: With #13 lurking I figured sticking to actual stored data was better?

File: README.md (hunk 2 above)
Comment (MattIPv4) [reply README.md:14]: https://developers.cloudflare.com/workers/wrangler/system-environment-variables/ specifically calls out that you can use a `.env` file

File: src/index.ts [hunk 7]
```diff
@@ -34,16 +34,28 @@ export default {
...
+      await env.KV.put('firstRun', new Date().toISOString());
+    }
 
+    await Promise.all(json.incidents.map(async incident => {
+      const kv = await env.KV.get<StoredIncident>(incident.id, 'json');
       console.log('-----\nIncident ' + incident.id + ' in KV: ' + (kv !== null) + '\n-----');
 
+      // On the first run, ignore any incidents that are already resolved
+      // We'll store them as skipped so we don't keep checking them
+      if (firstRun && incident.status === 'resolved') {
```
Comment (MattIPv4) [inline src/index.ts:49]:
```suggestion
      if (!kv && firstRun && incident.status === 'resolved') {
```
Probably shouldn't write a skip for an existing incident (for folks running this worker prior to this change)

**Review by WalshyDev — APPROVED** [review]
